apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend

        image: moulendra24/portfolio-backend:latest

        ports:
        - containerPort: 8080

        env:
        - name: DB_USERNAME
          value: "root"

        - name: DB_PASSWORD
          value: "root"

        - name: JWT_SECRET
          value: "mysecretkey123"